version: "3.8"
services:
    postgres-db:
        container_name: postgres-db
        image: postgres
        restart: always
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    pgadmin: # Better To Exclude In Production
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@postgres.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres-db

    # nest-app:
    #     container_name: raven-project
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     env_file: .env
    #     environment:
    #         - PORT=${PORT}
    #     ports:
    #         - "${PORT}:${PORT}"
    #     depends_on:
    #         - postgres-db
    #     volumes:
    #         - ./src:/app/src
